/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_duckmedia_ndksample_MyActivity */

#ifndef _Included_com_duckmedia_ndksample_MyActivity
#define _Included_com_duckmedia_ndksample_MyActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_duckmedia_ndksample_MyActivity
 * Method:    hello
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_duckmedia_ndksample_MyActivity_hello
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
