/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_duckmedia_ndksample_faceRecognizer_FaceRecognizerWrapper */

#ifndef _Included_com_duckmedia_ndksample_faceRecognizer_FaceRecognizerWrapper
#define _Included_com_duckmedia_ndksample_faceRecognizer_FaceRecognizerWrapper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_duckmedia_ndksample_faceRecognizer_FaceRecognizerWrapper
 * Method:    n_createLBPHFaceRecognizer
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_duckmedia_ndksample_faceRecognizer_FaceRecognizerWrapper_n_1createLBPHFaceRecognizer
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
